services:
  price_tracking_service:
    build:
      context: .
      dockerfile: ./price_tracking_service/Dockerfile
    image: cryptoalrt-price-tracking:latest
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8001:8000"
    working_dir: /app
    depends_on:
      broker:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cryptoalrt
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092

  notification_service:
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
    image: cryptoalrt-notification:latest
    command: bash -c "alembic upgrade head && faststream run infrastructures.broker.broker:app"
    working_dir: /app
    depends_on:
      broker:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - DB_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cryptoalrt
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092

  siws_login_service:
    build:
      context: .
      dockerfile: ./siws_login_service/Dockerfile
    image: cryptoalrt-siws-login:latest
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8003:8000"
    working_dir: /app
    depends_on:
      db:
        condition: service_started
    environment:
      - DB_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cryptoalrt
      - ALEMBIC_CONFIG=/app/src/infrastructures/alembic.ini

  portfolio_tracker:
    build:
      context: .
      dockerfile: ./portfolio_tracker/Dockerfile
    image: cryptoalrt-portfolio-tracker:latest
    command:
      - python
      - -m
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    ports:
      - "8004:8000"
    working_dir: /app
    depends_on:
      db:
        condition: service_started
    environment:
      - DB_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cryptoalrt

  worker:
    build:
      context: .
      dockerfile: ./price_tracking_service/Dockerfile
    image: cryptoalrt-worker:latest
    command:
      - taskiq
      - worker
      - --log-level=INFO
      - infrastructures.tasks.tasks:taskiq_broker
    depends_on:
      broker:
        condition: service_healthy
    restart: unless-stopped
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cryptoalrt
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092

  scheduler:
    build:
      context: .
      dockerfile: ./price_tracking_service/Dockerfile
    image: cryptoalrt-scheduler:latest
    command:
      - taskiq
      - scheduler
      - --log-level=INFO
      - infrastructures.tasks.tasks:scheduler
    depends_on:
      broker:
        condition: service_healthy
      redis:
        condition: service_started
      db:
        condition: service_started


    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cryptoalrt
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092

  db:
    image: "postgres:16"
    hostname: db
    environment:
      POSTGRES_DB: "cryptoalrt"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379"

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9094:9094"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9094 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  mail-dev:
      image: maildev/maildev
      restart: always
      environment:
        - TZ=Asia/Shanghai
        - MAILDEV_WEB_PORT=1080
        - MAILDEV_SMTP_PORT=1025
      ports:
        - "8080:1080"
        - "8025:1025"
      logging:
        driver: "json-file"
        options:
          max-size: "1m"

volumes:
  db-data:
